version: "3"

networks:
  local:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.dockerfile
    volumes:
      - "./config/nginx.vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./host/logs:/var/logs"
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - local
  
  php:
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    volumes:
      - "./src:/var/www"
    networks:
      - local

  # mysql:
  #   image: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=secret
  #   volumes:
  #     - "./database:/var/lib/mysql"
  #   networks:
  #     - local
  #   ports:
  #     - "3306:3306"